name: Trigger auto deployment for mobile-bff-hml

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ develop ]
    paths:
    - '**'
    - '.github/workflows/mobile-bff-hml-AutoDeployTrigger-d9a72c25-3289-41ab-82d6-d1bc0d3d1927.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MOBILEBFFHML_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: pubchat.azurecr.io
          registryUsername: ${{ secrets.MOBILEBFFHML_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MOBILEBFFHML_REGISTRY_PASSWORD }}
          containerAppName: mobile-bff-hml
          resourceGroup: rg-hml-app
          imageToBuild: pubchat.azurecr.io/mobile-bff-hml:${{ github.sha }}
          

     

